import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter, Link, NavLink, Route, Routes, useLocation } from 'react-router-dom'
import { ArrowRight, ArrowUpRight, BookOpen, Check, ChevronDown, CircleArrowRight, Clock3, GraduationCap, Leaf, Menu, MessageCircleHeart, Search, Send, Sprout, UsersRound, X } from 'lucide-react'
import './styles.css'

const images = {
  hero: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1600&q=85',
  portrait: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?auto=format&fit=crop&w=900&q=85',
  workshop: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=1100&q=85',
  story: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=1000&q=85',
}

// Replace the clearly labelled placeholders below with your details and content.
const site = { name: '[YOUR NAME]', email: '[YOUR EMAIL]', phone: '[YOUR PHONE]', location: '[YOUR LOCATION]' }
const nav = [{ label:'Home', to:'/' }, { label:'About', to:'/about' }, { label:'Services', to:'/services' }, { label:'Workshops', to:'/workshops' }, { label:'Resources', to:'/resources' }, { label:'Testimonials', to:'/testimonials' }, { label:'Contact', to:'/contact' }]
const services = [
  {icon: Sprout, title:'School consultation', text:'Thoughtful support to identify opportunities, set priorities, and build practical next steps.', includes:['Discovery conversations','School improvement planning','Ongoing thought partnership']},
  {icon: UsersRound, title:'Teacher development', text:'Training and mentoring that helps educators feel more confident, reflective, and equipped.', includes:['Teacher mentoring','Professional learning','Classroom observation']},
  {icon: BookOpen, title:'Academic & curriculum guidance', text:'Collaborative guidance around learning design, curriculum, assessment, and everyday teaching.', includes:['Curriculum planning','Learning outcomes','Teaching practices']},
  {icon: GraduationCap, title:'Workshops & training', text:'Interactive learning experiences shaped around the people and context in your school.', includes:['Leadership teams','Teaching teams','School communities']},
  {icon: Leaf, title:'Educational resources', text:'Useful ideas, frameworks, and materials that make strong practice easier to share.', includes:['Guides & tools','Classroom ideas','Reflection prompts']},
  {icon: MessageCircleHeart, title:'School improvement', text:'Sustainable approaches that keep teaching, learning, and human relationships at the centre.', includes:['Shared vision','Practical systems','Responsive change']},
]
const workshops = [
  {title:'Teaching for meaningful learning', audience:'Teachers & academic teams', duration:'Half or full day', format:'In-person / Online', text:'A practical exploration of purposeful classroom practices that support engagement and understanding.'},
  {title:'Leading learning with care', audience:'School leaders', duration:'90 minutes to full day', format:'School-based', text:'A reflective workshop for leadership teams looking to create the conditions where teachers and learners thrive.'},
  {title:'Designing a thoughtful curriculum', audience:'Curriculum & subject teams', duration:'Half day', format:'In-person / Online', text:'Build a shared language for planning learning that is coherent, relevant, and grounded in your context.'},
]
const resources = [
  {category:'Teaching', title:'Questions that open up learning', excerpt:'A simple guide to using questions that encourage students to think aloud and explore.', date:'[DATE]'},
  {category:'School Leadership', title:'Making space for reflection', excerpt:'A practical starting point for building reflective habits into busy school weeks.', date:'[DATE]'},
  {category:'Classroom Practice', title:'Small rituals, stronger classrooms', excerpt:'Six low-lift routines that support connection, focus, and learner ownership.', date:'[DATE]'},
  {category:'Teacher Development', title:'Peer learning that feels useful', excerpt:'A framework for moving collegial conversations from updates to genuine learning.', date:'[DATE]'},
  {category:'Curriculum', title:'Planning with the learner in mind', excerpt:'Prompts to help teams connect intentions, experiences, and evidence of learning.', date:'[DATE]'},
  {category:'Student Learning', title:'Noticing progress beyond marks', excerpt:'Ideas for making student growth visible in more human and useful ways.', date:'[DATE]'},
]
const testimonials = [
  {quote:'[YOUR NAME] created a generous, practical space for our team to think together. We left with ideas we could actually use.', by:'[NAME], Principal — [SCHOOL NAME]'},
  {quote:'The workshop felt deeply grounded in the reality of our classrooms. It was thoughtful, energising, and refreshingly useful.', by:'[NAME], Teacher — [SCHOOL NAME]'},
  {quote:'We valued the way our context was listened to before recommendations were made. The support felt like a true partnership.', by:'[NAME], School Leader — [SCHOOL NAME]'},
]
const stats = [{num:'[XX]+',label:'Years in education'}, {num:'[XX]+',label:'Workshops facilitated'}, {num:'[XX]+',label:'Schools supported'}, {num:'[XXXX]+',label:'Educators reached'}]

function ScrollTop(){ const {pathname}=useLocation(); useEffect(()=>{ const page=pathname==='/'?'Education & Growth':pathname.slice(1).replace(/(^|-)\w/g,x=>x.toUpperCase()); document.title=`${page} | ${site.name}`; window.scrollTo({top:0,behavior:'instant'}) },[pathname]); return null }
function Button({to,children,variant='primary'}:{to:string,children:React.ReactNode,variant?:'primary'|'secondary'|'text'}){ return <Link className={`button ${variant}`} to={to}>{children}{variant !== 'secondary' && <ArrowRight size={17}/>}</Link> }
function Header(){ const [open,setOpen]=useState(false); const {pathname}=useLocation(); useEffect(()=>setOpen(false),[pathname]); return <header className="header"><div className="shell nav"><Link className="brand" to="/"><span className="brand-mark"><Leaf size={18}/></span><span>{site.name}<small>Education & growth</small></span></Link><nav className={open?'navlinks open':'navlinks'} aria-label="Primary navigation">{nav.map(n=><NavLink key={n.to} to={n.to} end={n.to==='/' }>{n.label}</NavLink>)}<Link className="nav-cta" to="/contact">Work with me <ArrowUpRight size={15}/></Link></nav><button className="menu" aria-label={open?'Close navigation':'Open navigation'} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></header> }
function Footer(){ return <footer><div className="shell footer-grid"><div><Link className="brand light" to="/"><span className="brand-mark"><Leaf size={18}/></span><span>{site.name}<small>Education & growth</small></span></Link><p className="footer-intro">A calm, collaborative partner for schools that want learning to flourish.</p></div><div><h4>Explore</h4>{nav.slice(1,6).map(n=><Link key={n.to} to={n.to}>{n.label}</Link>)}</div><div><h4>Connect</h4><Link to="/contact">{site.email}</Link><span>{site.phone}</span><span>{site.location}</span></div><div className="footer-leaf"><Leaf size={56}/><p>Let learning take root.</p></div></div><div className="shell footbase"><span>© {new Date().getFullYear()} {site.name}. All rights reserved.</span><span>Placeholder site content — ready for your details.</span></div></footer> }
function PageHero({eyebrow,title,text,image}:{eyebrow:string,title:string,text:string,image?:string}){ return <section className="page-hero"><div className="shell page-hero-grid"><div><p className="eyebrow"><span></span>{eyebrow}</p><h1>{title}</h1><p className="lede">{text}</p></div>{image&&<div className="page-image"><img src={image} alt="Placeholder for your future photo" /></div>}</div></section> }
function SectionTitle({eyebrow,title,text}:{eyebrow:string,title:string,text?:string}){ return <div className="section-title"><p className="eyebrow"><span></span>{eyebrow}</p><h2>{title}</h2>{text&&<p>{text}</p>}</div> }
function ServiceCards({limit}:{limit?:number}){ return <div className="service-grid">{services.slice(0,limit).map(({icon:Icon,title,text})=><article className="service-card" key={title}><div className="icon"><Icon size={23}/></div><h3>{title}</h3><p>{text}</p><Link to="/services" className="quiet-link">Learn more <ArrowRight size={16}/></Link></article>)}</div> }
function Home(){ return <><section className="hero"><div className="shell hero-grid"><div className="hero-copy reveal"><p className="eyebrow light-eye"><span></span>Education consultancy</p><h1>Growing schools where learning <i>takes root.</i></h1><p>Practical consultation, thoughtful training, and useful resources for schools and educators who care about meaningful learning.</p><div className="hero-actions"><Button to="/contact">Work with me</Button><Button to="/resources" variant="secondary">Explore resources</Button></div><div className="hero-note"><Sprout size={16}/>Supporting schools with care, clarity, and context.</div></div><div className="hero-art"><img src={images.hero} alt="Teacher supporting children learning together in a bright classroom" /><div className="hero-tag"><span>01</span><p>Better learning<br/><b>begins together.</b></p></div></div></div><div className="hero-curve"></div></section>
<section className="section about-split"><div className="shell split-grid"><div className="photo-stack"><div className="organic-frame"></div><img src={images.portrait} alt="Professional portrait placeholder for [YOUR NAME]" loading="lazy"/><div className="photo-caption"><Sprout size={18}/><span>A thoughtful partner<br/>for your school.</span></div></div><div className="split-copy"><SectionTitle eyebrow="A little about me" title="Learning grows best when people feel seen."/><p>I’m <b>{site.name}</b>, an educator and school education consultant. I work alongside teachers and leaders to make the everyday work of learning more connected, reflective, and possible.</p><p className="muted">[YOUR BIO — Add a short, personal introduction here. Share what brings you to this work and the kind of impact you hope to have.]</p><Button to="/about" variant="text">Read more about me</Button></div></div></section>
<section className="section soft"><div className="shell"><SectionTitle eyebrow="Ways I can help" title="Support that meets your school where it is." text="Every school has its own story. The work begins with listening, then building something useful together."/><ServiceCards limit={3}/><div className="center"><Button to="/services" variant="text">Explore all services</Button></div></div></section>
<section className="approach"><div className="shell"><SectionTitle eyebrow="My approach" title="Small, considered steps toward lasting growth."/><div className="path">{[['01','Listen','Begin with people, context, and the questions that matter.'],['02','Understand','Make sense of what is already working and what needs attention.'],['03','Build together','Shape practical responses with your team, not for them.'],['04','Grow','Keep learning visible, sustainable, and responsive.']].map(([n,t,d])=><div className="path-step" key={n}><span>{n}</span><div className="path-icon"><Sprout size={22}/></div><h3>{t}</h3><p>{d}</p></div>)}</div></div></section>
<section className="section workshop-feature"><div className="shell workshop-grid"><div className="workshop-image"><img src={images.workshop} alt="Educators in a collaborative workshop" loading="lazy"/></div><div><SectionTitle eyebrow="Workshops & training" title="Make professional learning feel alive."/><p>From focused sessions to ongoing development, workshops are shaped to invite real conversation, useful experimentation, and shared momentum.</p><ul className="check-list">{['Teacher development','Classroom practices','School leadership','Curriculum & student learning'].map(x=><li key={x}><Check size={17}/>{x}</li>)}</ul><Button to="/workshops">Discuss a workshop</Button></div></div></section>
<Stats/><section className="section"><div className="shell"><div className="section-row"><SectionTitle eyebrow="From the resource shelf" title="Ideas for the work of teaching." text="A growing collection of practical thinking for educators and schools."/><Button to="/resources" variant="text">View all resources</Button></div><ResourceGrid limit={3}/></div></section><Testimonials/><CTA/></> }
function Stats(){return <section className="stats"><div className="shell stats-grid">{stats.map(s=><div key={s.label}><strong>{s.num}</strong><span>{s.label}</span></div>)}</div><p className="stats-note">Placeholder figures — replace with your actual impact numbers.</p></section>}
function ResourceGrid({limit}:{limit?:number}){ return <div className="resource-grid">{resources.slice(0,limit).map(r=><article className="resource-card" key={r.title}><div><span className="pill">{r.category}</span><span className="resource-date">{r.date}</span></div><h3>{r.title}</h3><p>{r.excerpt}</p><Link to="/resources" className="quiet-link">Read more <ArrowRight size={16}/></Link></article>)}</div>}
function Testimonials(){return <section className="testimonials"><div className="shell"><SectionTitle eyebrow="Kind words" title="In partnership with people who care."/><div className="quote-grid">{testimonials.map(t=><figure key={t.by}><span className="quote-mark">“</span><blockquote>{t.quote}</blockquote><figcaption>{t.by}</figcaption></figure>)}</div><div className="center"><Button to="/testimonials" variant="text">Read more testimonials</Button></div></div></section>}
function CTA(){return <section className="cta"><div className="shell cta-inner"><div><p className="eyebrow light-eye"><span></span>Start a conversation</p><h2>Let’s make space for better learning.</h2><p>Tell me a little about your school, your team, and what you’re hoping to explore.</p></div><Button to="/contact" variant="secondary">Get in touch</Button></div></section>}
function About(){return <><PageHero eyebrow="About me" title="A belief in education that feels deeply human." text="A space to share your story, your values, and the experiences that shape your work." image={images.portrait}/><section className="section"><div className="shell narrow story"><p className="story-kicker">My journey</p><h2>Rooted in curiosity, care, and the possibility of every learner.</h2><p>[YOUR BIO — This is where you can tell your story in your own voice. What first drew you to education? What keeps you invested in helping teachers, leaders, and schools grow?]</p><p>[YOUR PROFESSIONAL EXPERIENCE — Add a concise, human account of your teaching, leadership, and consulting experience here. Avoid a resume-like list; focus on the threads that connect your work.]</p></div></section><section className="section soft"><div className="shell values"><SectionTitle eyebrow="What I believe" title="The values I bring into every partnership."/>{[['Learning is relational','Strong learning starts with trust, curiosity, and a genuine sense of belonging.'],['Context matters','Useful ideas must make sense in the real, nuanced life of a school.'],['Growth is shared','Lasting change is built with people — through conversation, practice, and reflection.']].map(([t,d])=><article key={t}><Leaf size={22}/><h3>{t}</h3><p>{d}</p></article>)}</div></section><CTA/></>}
function Services(){return <><PageHero eyebrow="Services" title="Practical support for meaningful school growth." text="Explore flexible ways we can work together — always shaped by the needs, people, and pace of your school." image={images.story}/><section className="section"><div className="shell detailed-services">{services.map(({icon:Icon,title,text,includes},i)=><article key={title}><div className="detail-number">0{i+1}</div><div className="detail-icon"><Icon size={25}/></div><div><h2>{title}</h2><p>{text}</p></div><div><h4>What this can include</h4><ul>{includes.map(x=><li key={x}><Check size={15}/>{x}</li>)}</ul></div><div><h4>A considered outcome</h4><p className="small">Greater clarity, shared capacity, and useful next steps your team can keep building on.</p></div><Button to="/contact" variant="text">Start a conversation</Button></article>)}</div></section><CTA/></>}
function Workshops(){return <><PageHero eyebrow="Workshops & training" title="Professional learning with room to think, try, and grow." text="Engaging sessions for teachers, teams, and school leaders — adapted to the questions you are working with." image={images.workshop}/><section className="section"><div className="shell"><SectionTitle eyebrow="Ways to learn together" title="Workshop themes"/><div className="workshop-cards">{workshops.map(w=><article key={w.title}><span className="pill">{w.format}</span><h2>{w.title}</h2><p>{w.text}</p><dl><div><dt>For</dt><dd>{w.audience}</dd></div><div><dt>Duration</dt><dd><Clock3 size={14}/>{w.duration}</dd></div></dl><Button to="/contact" variant="text">Discuss this workshop</Button></article>)}</div></div></section><section className="section soft"><div className="shell narrow center"><SectionTitle eyebrow="Designed around your context" title="Looking for something specific?" text="Sessions can be tailored around your team’s questions, current priorities, and the kind of learning experience you want to create."/><Button to="/contact">Plan a workshop</Button></div></section></>}
function Resources(){const [query,setQuery]=useState('');const [active,setActive]=useState('All');const cats=['All',...new Set(resources.map(r=>r.category))];const shown=useMemo(()=>resources.filter(r=>(active==='All'||r.category===active)&&(`${r.title} ${r.excerpt}`).toLowerCase().includes(query.toLowerCase())),[active,query]);return <><PageHero eyebrow="Resources" title="Practical ideas for the everyday work of education." text="A growing library of articles, guides, frameworks, and classroom-friendly thinking."/><section className="section resources-page"><div className="shell"><div className="filters"><label className="search"><Search size={18}/><input aria-label="Search resources" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search resources"/></label><div className="filter-list">{cats.map(c=><button className={active===c?'active':''} onClick={()=>setActive(c)} key={c}>{c}</button>)}</div></div>{shown.length?<ResourceGridItems items={shown}/>:<p className="empty">No resources found. Try another search or filter.</p>}<button className="load-more">Load more <ChevronDown size={17}/></button></div></section></>}
function ResourceGridItems({items}:{items:typeof resources}){return <div className="resource-grid">{items.map(r=><article className="resource-card" key={r.title}><div><span className="pill">{r.category}</span><span className="resource-date">{r.date}</span></div><h3>{r.title}</h3><p>{r.excerpt}</p><Link to="/resources" className="quiet-link">Read more <ArrowRight size={16}/></Link></article>)}</div>}
function TestimonialsPage(){return <><PageHero eyebrow="Testimonials" title="What collaboration can feel like." text="Kind words from placeholder voices — replace these with feedback from your own school partners."/><Testimonials/><CTA/></>}
function Contact(){const [sent,setSent]=useState(false);function submit(e:React.FormEvent){e.preventDefault();setSent(true)}return <><PageHero eyebrow="Contact" title="Let’s talk about how I can support your school." text="Share a little about your context and what you’re hoping to explore. I’ll be in touch soon."/><section className="section contact"><div className="shell contact-grid"><aside><h2>Start with a conversation.</h2><p>Whether you have a clear brief or are simply beginning to think aloud, this is a welcoming place to begin.</p><div className="contact-detail"><span>Email</span><b>{site.email}</b></div><div className="contact-detail"><span>Phone</span><b>{site.phone}</b></div><div className="contact-detail"><span>Based in</span><b>{site.location}</b></div></aside><form onSubmit={submit} noValidate>{sent?<div className="form-success"><Check size={28}/><h2>Thank you.</h2><p>Your message has been noted. Connect this form to your preferred form provider before launch.</p></div>:<><div className="field-grid"><label>Name<input required placeholder="Your name"/></label><label>Email<input type="email" required placeholder="you@example.com"/></label></div><label>School / organisation<input placeholder="Where you work"/></label><label>Subject<input required placeholder="What would you like to discuss?"/></label><label>Message<textarea required rows={6} placeholder="Tell me a little about your school and what support you are looking for."></textarea></label><button className="submit" type="submit">Send message <Send size={17}/></button><p className="form-note">This demo form validates required fields in your browser. Connect it to your preferred form service to receive submissions.</p></>}</form></div></section></>}
function NotFound(){return <section className="not-found"><div><p className="eyebrow"><span></span>404</p><h1>This path needs a little tending.</h1><p>The page you’re looking for has moved, or perhaps hasn’t been planted yet.</p><Button to="/">Back to home</Button></div></section>}
function App(){return <BrowserRouter><ScrollTop/><Header/><main><Routes><Route path="/" element={<Home/>}/><Route path="/about" element={<About/>}/><Route path="/services" element={<Services/>}/><Route path="/workshops" element={<Workshops/>}/><Route path="/resources" element={<Resources/>}/><Route path="/testimonials" element={<TestimonialsPage/>}/><Route path="/contact" element={<Contact/>}/><Route path="*" element={<NotFound/>}/></Routes></main><Footer/></BrowserRouter>}
createRoot(document.getElementById('root')!).render(<App />)
